import { readFile, rename, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { assertCatalogRoutable, ROUTE_ORDER, ROUTES } from './model-routing.mjs'

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const catalogPath = join(packageRoot, 'generated/model-routes.json')
const patchPath = join(packageRoot, 'cordis.patch.yml')
const write = process.argv.includes('--write')
const check = process.argv.includes('--check')
if (write === check) throw new Error('Use exactly one of --write or --check')

function yamlString(value) {
  return JSON.stringify(value)
}

function renderModel(model, indent) {
  const lines = [
    `${indent}- id: ${yamlString(model.id)}`,
    `${indent}  name: ${yamlString(model.name)}`,
  ]
  if (model.contextWindow !== null) lines.push(`${indent}  contextWindow: ${model.contextWindow}`)
  if (model.maxTokens !== null) lines.push(`${indent}  maxTokens: ${model.maxTokens}`)
  lines.push(`${indent}  input: [${model.input.map(yamlString).join(', ')}]`)
  return lines
}

function render(catalog) {
  const lines = [
    '# GENERATED by scripts/render-profile.mjs from generated/model-routes.json.',
    '# Do not edit model rows by hand. The TokenLab public model detail contract owns protocol eligibility.',
    '# This bundle targets the existing DSH llm-pi-ai row because its protocol is route-scoped.',
    '',
    '- id: llm-pi-ai',
    '  config:',
    '    providers:',
  ]
  for (const routeName of ROUTE_ORDER) {
    const route = ROUTES[routeName]
    const models = catalog.routes[routeName]
    lines.push(
      `      ${route.provider}:`,
      '        apiKeyEnv: TOKENLAB_API_KEY',
      `        displayName: ${yamlString(route.displayName)}`,
      `        api: ${route.api}`,
      `        baseURL: ${route.baseURL}`,
      '        defaultContextWindow: 262144',
      '        defaultMaxTokens: 32768',
      '        defaultInput: [text]',
      '        streamIdleTimeoutMs: 120000',
      '        models:',
    )
    for (const model of models) lines.push(...renderModel(model, '          '))
  }
  lines.push(
    '',
    '- insert:',
    '    - id: tokenlab-async-tools',
    "      name: '@tokenlabai/dsh-provider'",
    '      config:',
    "        apiBase: !!js process.env.TOKENLAB_API_BASE ?? 'https://api.tokenlab.sh'",
    '        apiKeyEnv: TOKENLAB_API_KEY',
    '        defaultPollIntervalMs: 5000',
    '        defaultWaitMs: 900000',
    "        mcpToolProfile: !!js process.env.TOKENLAB_MCP_TOOL_PROFILE ?? 'core'",
    "        mcpSchemaMode: !!js process.env.TOKENLAB_MCP_SCHEMA_MODE ?? 'portable'",
    '        mcpToolCallTimeoutMs: 180000',
    '        mcpFailOnStartupError: true',
    '',
  )
  return lines.join('\n')
}

const catalog = JSON.parse(await readFile(catalogPath, 'utf8'))
assertCatalogRoutable(catalog)
const expected = render(catalog)
if (write) {
  const tempPath = `${patchPath}.tmp-${process.pid}`
  await writeFile(tempPath, expected, 'utf8')
  await rename(tempPath, patchPath)
  console.log(`Wrote ${patchPath}.`)
} else {
  const current = await readFile(patchPath, 'utf8')
  if (current !== expected) throw new Error('cordis.patch.yml is stale; run npm run routes:sync')
  console.log(`cordis.patch.yml matches ${catalog.counts.routed} routed models.`)
}
